---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{item}}"
  with_first_found:
    - files:
      - "vars/{{ansible_distribution_version}}.yml"
      - 'vars/main.yml'
      skip: 'true'
  tags:
    - install
    - hostname

#-------------------------------------------------------------------------------
# FILES
#-------------------------------------------------------------------------------

- name: 'template create hostname'
  template:
    src: "{{file_src_hostname}}"
    dest: "{{file_path_hostname}}"
    mode: "{{file_mode_hostname}}"
    owner: "{{file_owner_hostname}}"
    group: "{{file_group_hostname}}"
  notify: 'command set hostname'
  tags:
    - install
    - hostname
