---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{item}}"
  with_first_found:
    - files:
      - "vars/{{ansible_distribution_version}}.yml"
      - 'vars/main.yml'
      skip: 'true'
  tags:
    - disable
    - openntpd

#-------------------------------------------------------------------------------
# FILES
#-------------------------------------------------------------------------------

- name: 'file create ntpd.conf'
  template:
    src: "{{file_src_ntpd_conf}}"
    dest: "{{file_dst_ntpd_conf}}"
    mode: "{{file_mode_ntpd_conf}}"
    owner: "{{file_owner_ntpd_conf}}"
    group: "{{file_group_ntpd_conf}}"
  tags:
    - disable
    - openntpd

#-------------------------------------------------------------------------------
# SYSTEM
#-------------------------------------------------------------------------------

- name: 'service stop ntpd'
  service:
    state: 'stopped'
    enabled: 'no'
    name: "{{service_name_openntpd}}"
  tags:
    - disable
    - openntpd
