---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{item}}"
  with_first_found:
    - files:
      - "vars/{{ansible_distribution_version}}.yml"
      - 'vars/main.yml'
      skip: 'true'
  tags:
    - remove
    - main
    - openntpd

#-------------------------------------------------------------------------------
# PACKAGING
#-------------------------------------------------------------------------------

- name: 'package remove openntpd'
  package:
    state: 'absent'
    name: "{{package_name_openntpd}}"
  tags:
    - packaging
    - remove
    - main
    - openntpd

#-------------------------------------------------------------------------------
# FILES
#-------------------------------------------------------------------------------

- name: 'file remove ntpd.conf'
  file:
    state: 'absent'
    path: "{{file_path_ntpd_conf}}"
  tags:
    - files
    - remove
    - main
    - openntpd
