---

- name: 'task include install'
  include: install.yml
  when: not (findutils_state|match('false|no|remove|quiesce|inactive'))
  tags:
    - main
    - findutils

- name: 'task include remove'
  include: remove.yml
  when: (findutils_state|match('false|no|remove'))
  tags:
    - main
    - findutils
