---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{item}}"
  with_first_found:
    - files:
      - "vars/{{ansible_distribution_version}}.yml"
      - 'vars/main.yml'
      skip: 'true'
  tags:
    - remove
    - main
    - opensmtpd

#-------------------------------------------------------------------------------
# PACKAGING
#-------------------------------------------------------------------------------

- name: 'package remove opensmtpd'
  package:
    state: 'absent'
    name: "{{package_name_opensmtpd}}"
  tags:
    - remove
    - main
    - opensmtpd

#-------------------------------------------------------------------------------
# FILES
#-------------------------------------------------------------------------------

- name: 'file remove aliases'
  file:
    state: 'absent'
    path: "{{file_path_aliases}}"
  tags:
    - remove
    - main
    - opensmtpd

- name: 'file remove smtpd.conf'
  file:
    state: 'absent'
    path: "{{file_path_smtpd_conf}}"
  tags:
    - remove
    - main
    - opensmtpd
