---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{item}}"
  with_first_found:
    - files:
      - "vars/{{ansible_distribution_version}}.yml"
      - 'vars/main.yml'
      skip: 'true'
  tags:
    - install
    - main
    - openbsd_netcat

#-------------------------------------------------------------------------------
# PACKAGING
#-------------------------------------------------------------------------------

- name: 'package install openbsd-netcat'
  package:
    state: 'present'
    name: "{{package_name_openbsd_netcat}}"
  tags:
    - install
    - main
    - openbsd_netcat
