---

- name: 'task include install'
  import_tasks: install.yml
  when: not (openbsd_netcat_state|match('false|no|remove|quiesce|inactive'))
  tags:
    - main
    - openbsd_netcat

- name: 'task include remove'
  import_tasks: remove.yml
  when: (openbsd_netcat_state|match('false|no|remove'))
  tags:
    - main
    - openbsd_netcat
