---

- name: 'task include install'
  import_tasks: install.yml
  when: not (gnu_sed_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - gnu_sed

- name: 'task include remove'
  import_tasks: remove.yml
  when: (gnu_sed_state is match('false|no|remove'))
  tags:
    - gnu_sed
