---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{item}}"
  with_first_found:
    - files:
      - "vars/{{ansible_distribution_version}}.yml"
      - 'vars/main.yml'
      skip: 'true'
  tags:
    - install
    - inittab

#-------------------------------------------------------------------------------
# FILES
#-------------------------------------------------------------------------------

- name: 'template create inittab'
  template:
    src: "{{file_src_inittab}}"
    dest: "{{file_dst_inittab}}"
    mode: "{{file_mode_inittab}}"
    owner: "{{file_owner_inittab}}"
    group: "{{file_group_inittab}}"
  tags:
    - install
    - inittab
