---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{item}}"
  with_first_found:
    - files:
      - "vars/{{ansible_distribution_version}}.yml"
      - 'vars/main.yml'
      skip: 'true'
  tags:
    - install
    - apk

#-------------------------------------------------------------------------------
# FILES
#-------------------------------------------------------------------------------

- name: 'file create repositories'
  template:
    src: "{{file_src_repositories}}"
    dest: "{{file_dst_repositories}}"
    mode: "{{file_mode_repositories}}"
    owner: "{{file_owner_repositories}}"
    group: "{{file_group_repositories}}"
  notify:
    - 'command purge apk cache'
    - 'command update apk repository indexes'
  tags:
    - install
    - apk

#-------------------------------------------------------------------------------
# META
#-------------------------------------------------------------------------------

- name: 'meta flush handlers'
  meta: 'flush_handlers'
  tags:
    - install
    - apk
