---

- name: 'task include install'
  import_tasks: install.yml
  when: not (iproute2_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - iproute2

- name: 'task include remove'
  import_tasks: remove.yml
  when: (iproute2_state is match('false|no|remove'))
  tags:
    - iproute2
