---

- name: 'task include install'
  include: install.yml
  when: not (iproute2_state|match('false|no|remove|quiesce|inactive'))
  tags:
    - main
    - iproute2

- name: 'task include remove'
  include: remove.yml
  when: (iproute2_state|match('false|no|remove'))
  tags:
    - main
    - iproute2
