---

- name: 'task include install'
  include: install.yml
  when: not (iputils_state|match('false|no|remove|quiesce|inactive'))
  tags:
    - main
    - iputils

- name: 'task include remove'
  include: remove.yml
  when: (iputils_state|match('false|no|remove'))
  tags:
    - main
    - iputils
