---

- name: 'task include install'
  import_tasks: install.yml
  when: not (iputils_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - iputils

- name: 'task include remove'
  import_tasks: remove.yml
  when: (iputils_state is match('false|no|remove'))
  tags:
    - iputils
