---

- name: 'task include install'
  import_tasks: install.yml
  when: not (diffutils_state|match('false|no|remove|quiesce|inactive'))
  tags:
    - main
    - diffutils

- name: 'task include remove'
  import_tasks: remove.yml
  when: (diffutils_state|match('false|no|remove'))
  tags:
    - main
    - diffutils
