---

- name: 'task include install'
  include: install.yml
  when: not (gnu_awk_state|match('false|no|remove|quiesce|inactive'))
  tags:
    - main
    - gnu_awk

- name: 'task include remove'
  include: remove.yml
  when: (gnu_awk_state|match('false|no|remove'))
  tags:
    - main
    - gnu_awk
