---

- name: 'task include install'
  import_tasks: install.yml
  when: not (gnu_awk_state is match('false|no|remove|quiesce|inactive'))
  tags:
    - main
    - gnu_awk

- name: 'task include remove'
  import_tasks: remove.yml
  when: (gnu_awk_state is match('false|no|remove'))
  tags:
    - main
    - gnu_awk
