---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{item}}"
  with_first_found:
    - files:
      - "vars/{{ansible_distribution_version}}.yml"
      - 'vars/main.yml'
      skip: 'true'
  tags:
    - enable
    - busybox_ntpd

#-------------------------------------------------------------------------------
# FILES
#-------------------------------------------------------------------------------

- name: 'file create ntpd'
  template:
    src: "{{file_src_ntpd}}"
    dest: "{{file_dst_ntpd}}"
    mode: "{{file_mode_ntpd}}"
    owner: "{{file_owner_ntpd}}"
    group: "{{file_group_ntpd}}"
  notify: 'service restart busybox-ntpd'
  tags:
    - enable
    - busybox_ntpd

- name: 'line config busybox-ntpd_update-time'
  lineinfile:
    state: 'absent'
    line: "{{file_line_busybox_ntpd_update_time}} # Ansible: busybox-ntpd_update-time"
    regexp: "# Ansible: busybox-ntpd_update-time$"
    dest: "{{file_dst_busybox_ntpd_update_time}}"
  tags:
    - enable
    - busybox_ntpd

- name: 'file remove busybox-ntpd_update-time.sh'
  file:
    state: 'absent'
    path: "{{file_dst_busybox_ntpd_update_time_sh}}"
  tags:
    - enable
    - busybox_ntpd

#-------------------------------------------------------------------------------
# SYSTEM
#-------------------------------------------------------------------------------

- name: 'service start busybox-ntpd'
  service:
    state: 'started'
    enabled: 'yes'
    name: "{{service_name_busybox_ntpd}}"
  tags:
    - enable
    - busybox_ntpd
