---

- name: 'task include install'
  include: install.yml
  when: not (busybox_ntpd_state|match('false|no|remove|quiesce|inactive'))
  tags:
    - main
    - busybox_ntpd

- name: 'task include enable'
  include: enable.yml
  when: (busybox_ntpd_state|match('start|on|enable'))
  tags:
    - main
    - busybox_ntpd

- name: 'task include disable'
  include: disable.yml
  when: (busybox_ntpd_state|match('stop|off|disable'))
  tags:
    - main
    - busybox_ntpd

- name: 'task include cronjob'
  include: cronjob.yml
  when: (busybox_ntpd_state|match('cron|cronjob'))
  tags:
    - main
    - busybox_ntpd

- name: 'task include remove'
  include: remove.yml
  when: (busybox_ntpd_state|match('false|no|remove'))
  tags:
    - main
    - busybox_ntpd
