---

- name: 'task include install'
  import_tasks: install.yml
  when: not (busybox_ntpd_state|match('false|no|remove|quiesce|inactive'))
  tags:
    - main
    - busybox_ntpd

- name: 'task include enable'
  import_tasks: enable.yml
  when: (busybox_ntpd_state|match('start|on|enable'))
  tags:
    - main
    - busybox_ntpd

- name: 'task include disable'
  import_tasks: disable.yml
  when: (busybox_ntpd_state|match('stop|off|disable'))
  tags:
    - main
    - busybox_ntpd

- name: 'task include cronjob'
  import_tasks: cronjob.yml
  when: (busybox_ntpd_state|match('cron|cronjob'))
  tags:
    - main
    - busybox_ntpd

- name: 'task include remove'
  import_tasks: remove.yml
  when: (busybox_ntpd_state|match('false|no|remove'))
  tags:
    - main
    - busybox_ntpd
