---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{item}}"
  with_first_found:
    - files:
      - "vars/{{ansible_distribution_version}}.yml"
      - 'vars/main.yml'
      skip: 'true'
  tags:
    - remove
    - busybox_ntpd

#-------------------------------------------------------------------------------
# FILES
#-------------------------------------------------------------------------------

- name: 'line config busybox-ntpd_update-time'
  lineinfile:
    state: 'absent'
    line: "{{file_line_busybox_ntpd_update_time}} # Ansible: busybox-ntpd_update-time"
    regexp: "# Ansible: busybox-ntpd_update-time$"
    dest: "{{file_dst_busybox_ntpd_update_time}}"
  tags:
    - remove
    - busybox_ntpd

- name: 'file remove busybox-ntpd_update-time.sh'
  file:
    state: 'absent'
    path: "{{file_dst_busybox_ntpd_update_time_sh}}"
  tags:
    - remove
    - busybox_ntpd

- name: 'file remove ntdp-script.dir'
  file:
    state: 'absent'
    path: "{{file_dst_busybox_ntpd_script_dir}}"
  tags:
    - remove
    - busybox_ntpd

- name: 'file remove ntpd'
  file:
    state: 'absent'
    path: "{{file_dst_ntpd}}"
  tags:
    - remove
    - busybox_ntpd
